### ISSUE TITLE
LogError and LogInfo in main.c

### ISSUE THREAD

**Issue by MaHaXWS** [Azure-Samples/iot-hub-c-raspberrypi-client-app#17]
Hi
For some reason I can not run the app. The errors are:  undefined reference to `LogError' and  undefined reference to `LogInfo'. Where do I find these functions. Or Is there the posibility to replace them with printf.

I tried everything with Raspberry 2B und jessy

Best 
MaHa

**Comment by jchidley** [comment]
I have exactly the same problem - running on a Pi3 with latest upgrade to raspbian

**Comment by mkeyanmech** [comment]
I have same issue as well, any updates will help

**Comment by SLdragon** [comment]
@MaHaXWS @jchidley  @mkeyanmech  Thanks for reporting this issue, this issue is because the latest iot SDK remove the LogError function. 
You can comment this function in the code to fix this issue.

**Comment by SLdragon** [comment]
fixed
