### ISSUE TITLE
Error while running setup.sh

### ISSUE THREAD

**Issue by mkeyanmech** [Azure-Samples/iot-hub-c-raspberrypi-client-app#18]
Hello all 
I get below errors while running setup.sh, appreciate any help or suggestions on how to fix the error

CMakeFiles/app.dir/main.c.o:/home/pi/iot-hub-c-raspberrypi-client-app/main.c:334: more undefined references to `LogError' follow
collect2: error: ld returned 1 exit status
CMakeFiles/app.dir/build.make:172: recipe for target 'app' failed
make[2]: *** [app] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/app.dir/all' failed
make[1]: *** [CMakeFiles/app.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by SLdragon** [comment]
Fixed
