### ISSUE TITLE
Error creating "app" file during install due to some json error

### ISSUE THREAD

**Issue by handcyclist** [Azure-Samples/iot-hub-c-raspberrypi-client-app#23]
I had installed the iot-hub-c-raspberry-client-app two or three weeks ago and it worked although it gave me the following error (for the 2nd message only) but then it continued running: Error: Time:... File:/root/Source/azure-iot-sdk-c/serializer/src/multitree.c Func:MultiTree_GetLeafValue Line:728 (result = MULTITREE_CHILD_NOT_FOUND)
I tried reinstalling a bunch of times during the last day or two and kept failing creating the "app" file due to some json error.
I realized that the latest branch of the azure-iot-sdk-c had a commit done yesterday (2018Mar05).
It then occurred to me to try the version lts_01_2018 of the azure-iot-sdk-c; I made 2 changes to the setup.sh file:
1- to install on /home/pi instead on /root
2- to use lts_01_2018
The install completed and ran, although with the same MULTITREE_CHILD_NOT_FOUND error.
These are the changes I did to the setup.sh file:

#On Raspbian Stretch precompiled sdk from ppa is no good. Lets compile it manually
#cd ~
cd /home/pi
mkdir Source
cd Source
#git clone --recursive https://github.com/azure/azure-iot-sdk-c.git
git clone -b lts_01_2018 --recursive https://github.com/azure/azure-iot-sdk-c.git

Regards,
handcyclist

**Comment by SLdragon** [comment]
This issue is same as this issue:
https://github.com/Azure-Samples/iot-hub-c-raspberrypi-client-app/issues/24

**Comment by handcyclist** [comment]
No, no, it is not the same error as the MULTI TREE error.
The JSON error does not allow the "app" to be created, it fails compiling/linking just before creating the "app".
I re-run setup.sh to load the January 2018 LTS version of the "c" sdk, and that version allows the "app" to be created.
Basically the problem is that te raspberry app does not workvwith the latest "c" sdk.
Anyway, thank you for responding but this issue should not be closed.
Sorry for not explaining clearly

**Comment by SLdragon** [comment]
@handcyclist do you mean this error is related to the parson library?
I explain it in this isssue: 
https://github.com/Azure-Samples/iot-hub-c-raspberrypi-client-app/issues/25
