### ISSUE TITLE
Recipe for target app failed

### ISSUE THREAD

**Issue by Alberto-Vega-MSFT** [Azure-Samples/iot-hub-c-raspberrypi-client-app#27]
This issue seems to be the same from #25  I saw that there is a workaround  that I will try at some point. Hoping this gets resolved for future users trying the tutorial @SLdragon any insights on this? Below are the errors

-- Configuring done
-- Generating done
-- Build files have been written to: /home/pi/iot-hub-c-raspberrypi-client-app/iot-hub-c-raspberrypi-client-app
[ 20%] Linking C executable app
//usr/local/lib/libiothub_client.a(iothub_client_ll_uploadtoblob.c.o): In function `IoTHubClient_LL_UploadToBlob_step1and2':
iothub_client_ll_uploadtoblob.c:(.text+0x1018): undefined reference to `json_parse_string'
iothub_client_ll_uploadtoblob.c:(.text+0x1084): undefined reference to `json_value_get_object'
iothub_client_ll_uploadtoblob.c:(.text+0x10fc): undefined reference to `json_object_get_string'
iothub_client_ll_uploadtoblob.c:(.text+0x11e0): undefined reference to `json_object_get_string'
iothub_client_ll_uploadtoblob.c:(.text+0x1258): undefined reference to `json_object_get_string'
iothub_client_ll_uploadtoblob.c:(.text+0x12d0): undefined reference to `json_object_get_string'
iothub_client_ll_uploadtoblob.c:(.text+0x1348): undefined reference to `json_object_get_string'
iothub_client_ll_uploadtoblob.c:(.text+0x1814): undefined reference to `json_value_free'
collect2: error: ld returned 1 exit status
CMakeFiles/app.dir/build.make:172: recipe for target 'app' failed
make[2]: *** [app] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/app.dir/all' failed
make[1]: *** [CMakeFiles/app.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by yzhong94** [comment]
Thanks for creating the PR!  Merged and confirmed that it's working.
